version: '3'

services:
  app:
    build: .
    environment:
      - PORT=9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GLOBAL_API_PREFIX=api/v1
      - SWAGGER_USER=admin
      - SWAGGER_PASSWORD=admin
      - LOG_LEVEL=log,error,warn,debug,verbose
    ports:
      - '9000:9000'
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
